--- #YAML:1.0
name:               Math-SimpleHisto-XS
version:            1.11
abstract:           Simple histogramming, but kinda fast
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::ParseXS:  0.2201
    Test::More:         0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
